name: Build Tibia OTS Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Boost
        uses: MarkusJx/install-boost@v2
        with:
          boost_version: '1.71.0'  # Wybierz wersję Boost zgodną z Twoim projektem

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: |
          cd vc14
          cmake -G "NMake Makefiles" -A x64 .. -DBOOST_ROOT=${{ env.BOOST_ROOT }}

      - name: Build project
        run: |
          cd vc14
          nmake

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilverMoon.exe
          path: vc14/Release/SilverMoon.exe
