name: Build Tibia OTS Client

on:
  push:
    branches:
      - main  # Uruchom workflow po pushu na gałąź main
  pull_request:
    branches:
      - main  # Uruchom workflow po PR do gałęzi main

jobs:
  build:
    runs-on: windows-latest  # Użyj systemu Windows do budowania

    steps:
      # Krok 1: Pobierz repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # Krok 2: Skonfiguruj MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      # Krok 3: Zainstaluj CMake
      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      # Krok 4: Zbuduj projekt
      - name: Build project
        run: |
          # Przejdź do katalogu z projektem
          cd vc14  # Zmień na odpowiedni katalog, jeśli jest inny
          # Uruchom CMake, wskazując katalog główny jako źródło
          cmake -G "Visual Studio 17 2022" -A x64 ../..
          # Uruchom MSBuild
          msbuild.exe "otclient.sln" /p:Configuration=Release

      # Krok 5: Przesuń plik wykonywalny do artefaktów
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilverMoon.exe
          path: vc14/Release/SilverMoon.exe  # Zmień na ścieżkę do swojego pliku .exe
