name: Build Tibia OTS Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Boost
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          boost_version: '1.76.0'  # Ensure this matches your project's requirements

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Update Windows SDK version
        run: |
          $projectFile = 'vc14\otclient.vcxproj'
          (Get-Content $projectFile) -replace '<WindowsTargetPlatformVersion>.*</WindowsTargetPlatformVersion>', '<WindowsTargetPlatformVersion>10.0.19041.0</WindowsTargetPlatformVersion>' | Set-Content $projectFile

      - name: Configure CMake
        run: |
          cd vc14
          cmake -G "Visual Studio 17 2022" -A x64 .. -DBOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }} -DBOOST_LIBRARYDIR=${{ steps.install-boost.outputs.BOOST_ROOT }}/lib

      - name: Build project
        run: |
          cd vc14
          msbuild otclient.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilverMoon.exe
          path: vc14/Release/SilverMoon.exe