name: Build Tibia OTS Client

on:
  push:
    branches:
      - main  # Uruchom workflow po pushu na gałąź main
  pull_request:
    branches:
      - main  # Uruchom workflow po PR do gałęzi main

jobs:
  build:
    runs-on: windows-latest  # Użyj systemu Windows do budowania

    steps:
      # Krok 1: Pobierz repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # Krok 2: Skonfiguruj środowisko budowania (np. CMake, Visual Studio)
      - name: Set up build environment
        run: |
          # Zainstaluj wymagane narzędzia (np. CMake, Visual Studio)
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install visualstudio2022community --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop" -y

          # Dodaj narzędzia MSBuild do ścieżki systemowej
          $vsPath = "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
          echo "##vso[task.prependpath]$vsPath"

      # Krok 3: Zbuduj projekt
      - name: Build project
        run: |
          # Przejdź do katalogu z projektem
          cd src/client
          # Uruchom CMake
          cmake -G "Visual Studio 17 2022" -A x64 .
          # Uruchom MSBuild
          msbuild Tibia_OTS_Client.sln /p:Configuration=Release

      # Krok 4: Przesuń plik wykonywalny do artefaktów
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilverMoon.exe
          path: src/client/Release/SilverMoon.exe  # Zmień na ścieżkę do swojego pliku .exe