name: SilverMoonRP_Client

on:
  push:
    branches:
      - main  # Uruchom workflow po pushu na gałąź main
  pull_request:
    branches:
      - main  # Uruchom workflow po PR do gałęzi main

jobs:
  build:
    runs-on: windows-latest  # Użyj systemu Windows do budowania

    steps:
      # Krok 1: Pobierz repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # Krok 2: Skonfiguruj środowisko budowania (np. CMake, MSBuild)
      - name: Set up build environment
        run: |
          # Zainstaluj wymagane narzędzia (np. CMake, Visual Studio)
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install visualstudio2022community --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop"
          refreshenv

      # Krok 3: Zbuduj projekt
      - name: Build project
        run: |
          # Przejdź do katalogu z projektem
          cd vc14  # Zmień na odpowiedni katalog
          # Uruchom CMake i MSBuild (dostosuj do swojego projektu)
          cmake -G "Visual Studio 17 2022" -A x64 ..
          msbuild ALL_BUILD.vcxproj /p:Configuration=Release

      # Krok 4: Przesuń plik wykonywalny do artefaktów
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SilverMoon.exe
          path: vc14/Release/SilverMoon.exe  # Zmień na ścieżkę do swojego pliku .exe