name: Build Tibia OTS Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Boost
        uses: egor-tensin/build-boost-action@v2
        with:
          version: '1.76.0'  # Wersja Boost do zainstalowania

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilverMoon.exe
          path: build/Release/SilverMoon.exe  # Upewnij się, że ścieżka jest poprawna
